### ISSUE TITLE
Suggestion: Using GitHub cache action to cache the downloaded files between CI runs

### ISSUE THREAD

**Issue by ravenexp** [mstorsjo/msvc-wine#113]
GitHub Action CI provides basic support for caching downloaded dependencies:
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action

OTOH, the `build.yml` workflow file contains the following lines:

```yaml
      - name: Test using the installed tools
        run: |
          test/test.sh $(pwd)/msvc
      # Intentionally not storing any artifacts with the downloaded tools;
      # the installed files aren't redistributable!
```

I've been working on the automated WDK setup, which adds another 700 MB to the total downloads size, this will increase the load on the Microsoft servers even more if added to the default CI pipeline.

Is it ok to use GitHub Actions caching given that the downloaded files are not redistributable?
