### ISSUE TITLE
CLion support

### ISSUE THREAD

**Issue by TaxMachine** [mstorsjo/msvc-wine#175]
I'm trying to get it work as a CLion Toolchain but when I set the compiler like this

CMake: Bundled
Build Tool: Detected: Ninja
C Compiler: /home/taxmachine/msvc/bin/x86/cl
C++ Compiler: /home/taxmachine/msvc/bin/x86/cl
Debugger: Bundled GDB

I get this error "Test CMake run finished with errors"
```
-- The C compiler identification is MSVC 19.42.34435.0
-- The CXX compiler identification is MSVC 19.42.34435.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /home/taxmachine/msvc/bin/x86/cl
-- Check for working C compiler: /home/taxmachine/msvc/bin/x86/cl - broken
CMake Error at /home/taxmachine/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/home/taxmachine/msvc/bin/x86/cl"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/tmp/cmake_check_environment/_build143599532081475529/CMakeFiles/CMakeScratch/TryCompile-GwiSiI'
    
    Run Build Command(s): /home/taxmachine/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_d16ca
    [1/2] /home/taxmachine/msvc/bin/x86/cl    -o CMakeFiles/cmTC_d16ca.dir/testCCompiler.c.o -c /tmp/cmake_check_environment/_build143599532081475529/CMakeFiles/CMakeScratch/TryCompile-GwiSiI/testCCompiler.c
    Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34435 for x86
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
    testCCompiler.c
    [2/2] : && /home/taxmachine/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f libcmTC_d16ca.a && /home/taxmachine/msvc/bin/x86/lib qc libcmTC_d16ca.a  CMakeFiles/cmTC_d16ca.dir/testCCompiler.c.o && :
    FAILED: libcmTC_d16ca.a 
    : && /home/taxmachine/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f libcmTC_d16ca.a && /home/taxmachine/msvc/bin/x86/lib qc libcmTC_d16ca.a  CMakeFiles/cmTC_d16ca.dir/testCCompiler.c.o && :
    Microsoft (R) Library Manager Version 14.42.34435.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    LINK : fatal error LNK1181: cannot open input file 'qc'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!

Error code: 1
```

**Comment by TaxMachine** [comment]
my CMakeLists looks like this

```cmake
cmake_minimum_required(VERSION 3.30)
project(some_project)

set(CMAKE_GENERATOR_PLATFORM Win32)  # Force 32-bit compilation
set(CMAKE_SYSTEM_PROCESSOR x86)      # Specify x86 architecture
set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_RELEASE} /MTd")
file(GLOB_RECURSE SOURCES "src/**")


add_library(some_project SHARED ${SOURCES})

target_link_libraries(some_project PRIVATE "${CMAKE_SOURCE_DIR}\\libs\\detours.lib")
```

**Comment by mstorsjo** [comment]
I think some of these variables need to be set already at the time of the `project()` statement, either set on the command line or via a cmake toolchain file. Or what if you move the `CMAKE_SYSTEM_NAME`, `CMAKE_SYSTEM_PROCESSOR` and `CMAKE_GENERATOR_PLATFORM` options to the top of the file before `project()`?

**Comment by TaxMachine** [comment]
nop same error

**Comment by U65535F** [comment]
@mstorsjo

**Comment by jys1670** [comment]
FYI: The latest CLion works fine for me with MSVC and Clang. I tested it with a minimalistic C++23 project (`CMakeLists.txt` contains no special options, except for the `CMAKE_EXPERIMENTAL_CXX_IMPORT_STD`), bundled CMake and Ninja Multi-Config as the generator.

![Image](https://github.com/user-attachments/assets/d4b19885-ddcc-46d7-a9d2-110cb3a20aa4)

With Clang, you can even get a seamless debugging experience (compile with dwarf debug info, start `gdbserver.exe` in wine, remote connect from CLion)

**Comment by 1Kuso4ek1** [comment]
So, my current workaround as of now for the `clang-cl`.  

custom compiler .yaml file:
<details>
<summary>clang-cl.yaml</summary>

```yaml
compilers:
  - description: clang-cl
    match-language: CPP
    match-compiler-exe: (.*/)?clang-cl-21(\.exe)?
    code-insight-target-name: x86_64
    include-dirs:
      - ${user-home}/msvc/vc/tools/msvc/14.44.35207/atlmfc/include
      - ${user-home}/msvc/vc/tools/msvc/14.44.35207/include
      - ${user-home}/msvc/kits/10/include/10.0.26100.0/shared
      - ${user-home}/msvc/kits/10/include/10.0.26100.0/ucrt
      - ${user-home}/msvc/kits/10/include/10.0.26100.0/um
      - ${user-home}/msvc/kits/10/include/10.0.26100.0/winrt
    defines-text: "
#define __cplusplus 202002L
#define _CPPRTTI 1
#define __cpp_ref_qualifiers 200710L
#define __cpp_init_captures 201304L
#define __STDCPP_DEFAULT_NEW_ALIGNMENT__ 16ull
#define __cpp_rtti 199711L
#define _M_X64 100
#define __cpp_decltype_auto 201304L
#define _MSC_EXTENSIONS 1
#define _MSVC_LANG 201402L
#define __cpp_binary_literals 201304L
#define __cpp_constexpr 201304L
#define _MSC_BUILD 0
#define __cpp_attributes 200809L
#define __cpp_inheriting_constructors 200802L
#define __cpp_generic_lambdas 201304L
#define __cpp_variable_templates 201304L
#define __cpp_nsdmi 200809L
#define _NATIVE_WCHAR_T_DEFINED 1
#define __BOOL_DEFINED 1
#define _WIN64 1
#define __cpp_sized_deallocation 201309L
#define __cpp_threadsafe_static_init 200806L
#define _HAS_CHAR16_T_LANGUAGE_SUPPORT 1
#define __cpp_initializer_lists 200806L
#define _IS_ASSIGNABLE_NOCHECK_SUPPORTED 1
#define __cpp_static_assert 200410L
#define _M_AMD64 100
#define __cpp_return_type_deduction 201304L
#define __cpp_enumerator_attributes 201411L
#define __cpp_decltype 200707L
#define _CONSTEXPR_CHAR_TRAITS_SUPPORTED 1
#define _MT 1
#define _WCHAR_T_DEFINED 1
#define _MSVC_WARNING_LEVEL 1L
#define __cpp_alias_templates 200704L
#define __cpp_lambdas 200907L
#define __STDC_HOSTED__ 1
#define __cpp_user_defined_literals 200809L
#define __cpp_rvalue_references 200610L
#define _NATIVE_NULLPTR_SUPPORTED 1
#define __cpp_namespace_attributes 201411L
#define __STDCPP_THREADS__ 1
#define _MSC_FULL_VER 194435222
#define _MSC_VER 1944
#define _MSVC_TRADITIONAL 0
#define __cpp_range_based_for 200907L
#define _MSVC_CONSTEXPR_ATTRIBUTE 1
#define __cpp_raw_strings 200710L
#define __cpp_unicode_literals 200710L
#define __cpp_unicode_characters 200704L
#define _MSVC_EXECUTION_CHARACTER_SET 1251
#define _INTEGRAL_MAX_BITS 64
#define __cpp_aggregate_nsdmi 201304L
#define _WIN32 1
#define _CRT_USE_BUILTIN_OFFSETOF 1
#define __cpp_variadic_templates 200704L
#define __cpp_delegating_constructors 200604L
#define __cdecl
#define __stdcall
#define __fastcall
#define __vectorcall
#define __thiscall
#define __clrcall"
```  

(Emptying the calling-convention defines is mandatory. Seems like CLion Nova doesn't care that clang-cl is compatible with that)

</details>

The result (no errors and all of the ide features seem to be available):

<img width="1920" height="1046" alt="Image" src="https://github.com/user-attachments/assets/9e4d8f93-2c98-49d6-b27c-a0225b6cf8d5" />
